'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class AplicarPrueba

    '''<summary>
    '''Menu1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Menu1 As Global.System.Web.UI.WebControls.Menu

    '''<summary>
    '''MultiView1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MultiView1 As Global.System.Web.UI.WebControls.MultiView

    '''<summary>
    '''Tab1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Tab1 As Global.System.Web.UI.WebControls.View

    '''<summary>
    '''StudentName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents StudentName As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''StudentNumber control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents StudentNumber As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Stu_Gender control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Stu_Gender As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''XmlGenero control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents XmlGenero As Global.System.Web.UI.WebControls.XmlDataSource

    '''<summary>
    '''Stu_Birthday control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Stu_Birthday As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Stu_Email control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Stu_Email As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Stu_Phone control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Stu_Phone As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Stu_Direccion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Stu_Direccion As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Stu_Postal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Stu_Postal As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Stu_Department control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Stu_Department As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''XmlDataSource3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents XmlDataSource3 As Global.System.Web.UI.WebControls.XmlDataSource

    '''<summary>
    '''Stu_Year control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Stu_Year As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''XmlDataSource1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents XmlDataSource1 As Global.System.Web.UI.WebControls.XmlDataSource

    '''<summary>
    '''Stu_Igs control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Stu_Igs As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''XmlIGS control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents XmlIGS As Global.System.Web.UI.WebControls.XmlDataSource

    '''<summary>
    '''Stu_Certificate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Stu_Certificate As Global.System.Web.UI.WebControls.FileUpload

    '''<summary>
    '''lbl_Status control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_Status As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Stu_Status control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Stu_Status As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Stu_Authorization control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Stu_Authorization As Global.System.Web.UI.WebControls.RadioButtonList

    '''<summary>
    '''XmlSINO control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents XmlSINO As Global.System.Web.UI.WebControls.XmlDataSource

    '''<summary>
    '''btnGuardarEstudiante control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnGuardarEstudiante As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnActualizarEstudiante control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnActualizarEstudiante As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''Tab2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Tab2 As Global.System.Web.UI.WebControls.View

    '''<summary>
    '''Stu_Ensayo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Stu_Ensayo As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''btnGuardarEnsayo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnGuardarEnsayo As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''Tab3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Tab3 As Global.System.Web.UI.WebControls.View

    '''<summary>
    '''eval_Nombre1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents eval_Nombre1 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''eval_Ocupacion1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents eval_Ocupacion1 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''eval_Trabajo1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents eval_Trabajo1 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''eval_Telpersonal1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents eval_Telpersonal1 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''eval_Teltrabajo1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents eval_Teltrabajo1 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''eval_Email1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents eval_Email1 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''eval_Nombre2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents eval_Nombre2 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''eval_Ocupacion2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents eval_Ocupacion2 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''eval_Trabajo2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents eval_Trabajo2 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''eval_Telpersonal2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents eval_Telpersonal2 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''eval_Teltrabajo2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents eval_Teltrabajo2 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''eval_Email2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents eval_Email2 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''eval_Nombre3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents eval_Nombre3 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''eval_Ocupacion3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents eval_Ocupacion3 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''eval_Trabajo3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents eval_Trabajo3 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''eval_Telpersonal3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents eval_Telpersonal3 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''eval_Teltrabajo3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents eval_Teltrabajo3 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''eval_Email3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents eval_Email3 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''btnEvalaudores control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnEvalaudores As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''Tab4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Tab4 As Global.System.Web.UI.WebControls.View

    '''<summary>
    '''infad_Comites control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents infad_Comites As Global.System.Web.UI.WebControls.CheckBoxList

    '''<summary>
    '''XmlDcomites control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents XmlDcomites As Global.System.Web.UI.WebControls.XmlDataSource

    '''<summary>
    '''infad_Excursiones_edu control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents infad_Excursiones_edu As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''infad_Talleres control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents infad_Talleres As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''infad_Talleresde control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents infad_Talleresde As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''infad_Conferencias control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents infad_Conferencias As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''infad_Conferenciasde control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents infad_Conferenciasde As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''infad_Convenciones control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents infad_Convenciones As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''infad_Convencionesde control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents infad_Convencionesde As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''infad_actividad control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents infad_actividad As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''infad_actividadesde control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents infad_actividadesde As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''infad_otro control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents infad_otro As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''btnGuardarInfoAdicional control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnGuardarInfoAdicional As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnSometer control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSometer As Global.System.Web.UI.WebControls.Button
End Class
