'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Doc_Mem

    '''<summary>
    '''Asedoc_nombre control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Asedoc_nombre As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Asedoc_Titulo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Asedoc_Titulo As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Asedoc_Departamento control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Asedoc_Departamento As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Asedoc_email control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Asedoc_email As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Asedoc_Descripcion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Asedoc_Descripcion As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Asedoc_Status control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Asedoc_Status As Global.System.Web.UI.WebControls.Label
End Class
