'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Evaluacion

    '''<summary>
    '''form1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents form1 As Global.System.Web.UI.HtmlControls.HtmlForm

    '''<summary>
    '''Eval_NombreEstudiante control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Eval_NombreEstudiante As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Eval_NumeroEstudiante control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Eval_NumeroEstudiante As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Eval_AsociacionEst control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Eval_AsociacionEst As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''Eval_AsociacionData control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Eval_AsociacionData As Global.System.Web.UI.WebControls.XmlDataSource

    '''<summary>
    '''Eval_ConoceEst control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Eval_ConoceEst As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''Eval_ConoceData control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Eval_ConoceData As Global.System.Web.UI.WebControls.XmlDataSource

    '''<summary>
    '''Eval_tiempo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Eval_tiempo As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''Eval_tiempoData control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Eval_tiempoData As Global.System.Web.UI.WebControls.XmlDataSource

    '''<summary>
    '''Eval_OpinionProfEst control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Eval_OpinionProfEst As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Eval_FaltaEst control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Eval_FaltaEst As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''Eval_ConocimientoData control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Eval_ConocimientoData As Global.System.Web.UI.WebControls.XmlDataSource

    '''<summary>
    '''Eval_FaltaEsttxt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Eval_FaltaEsttxt As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Eval_Tarea control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Eval_Tarea As Global.System.Web.UI.WebControls.RadioButtonList

    '''<summary>
    '''Eval_tareaData control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Eval_tareaData As Global.System.Web.UI.WebControls.XmlDataSource

    '''<summary>
    '''Eval_Cumplimiento control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Eval_Cumplimiento As Global.System.Web.UI.WebControls.RadioButtonList

    '''<summary>
    '''Eval_TiempoTrabData control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Eval_TiempoTrabData As Global.System.Web.UI.WebControls.XmlDataSource

    '''<summary>
    '''Eval_UsoTiempo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Eval_UsoTiempo As Global.System.Web.UI.WebControls.RadioButtonList

    '''<summary>
    '''Eval_TiempoBienData control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Eval_TiempoBienData As Global.System.Web.UI.WebControls.XmlDataSource

    '''<summary>
    '''Eval_Horario control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Eval_Horario As Global.System.Web.UI.WebControls.RadioButtonList

    '''<summary>
    '''Eval_HorarioData control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Eval_HorarioData As Global.System.Web.UI.WebControls.XmlDataSource

    '''<summary>
    '''Eval_OrdenEstudiante control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Eval_OrdenEstudiante As Global.System.Web.UI.WebControls.RadioButtonList

    '''<summary>
    '''Eval_OrdenadoData control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Eval_OrdenadoData As Global.System.Web.UI.WebControls.XmlDataSource

    '''<summary>
    '''Eval_Procedimiento control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Eval_Procedimiento As Global.System.Web.UI.WebControls.RadioButtonList

    '''<summary>
    '''Eval_ProcedimientoData control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Eval_ProcedimientoData As Global.System.Web.UI.WebControls.XmlDataSource

    '''<summary>
    '''Eval_AjustaNormas control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Eval_AjustaNormas As Global.System.Web.UI.WebControls.RadioButtonList

    '''<summary>
    '''Eval_AjustaNormasData control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Eval_AjustaNormasData As Global.System.Web.UI.WebControls.XmlDataSource

    '''<summary>
    '''Eval_CalidadTrbajo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Eval_CalidadTrbajo As Global.System.Web.UI.WebControls.RadioButtonList

    '''<summary>
    '''Eval_trabajoData control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Eval_trabajoData As Global.System.Web.UI.WebControls.XmlDataSource

    '''<summary>
    '''Eval_DeleganResponsabilidad control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Eval_DeleganResponsabilidad As Global.System.Web.UI.WebControls.RadioButtonList

    '''<summary>
    '''Eval_ResponsabilidadData control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Eval_ResponsabilidadData As Global.System.Web.UI.WebControls.XmlDataSource

    '''<summary>
    '''Eval_Presion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Eval_Presion As Global.System.Web.UI.WebControls.RadioButtonList

    '''<summary>
    '''Eval_PresionData control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Eval_PresionData As Global.System.Web.UI.WebControls.XmlDataSource

    '''<summary>
    '''Eval_Habilidad_Analisis_Resolver control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Eval_Habilidad_Analisis_Resolver As Global.System.Web.UI.WebControls.RadioButtonList

    '''<summary>
    '''Eval_habilidadesData control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Eval_habilidadesData As Global.System.Web.UI.WebControls.XmlDataSource

    '''<summary>
    '''Eval_EnfrentarRetos control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Eval_EnfrentarRetos As Global.System.Web.UI.WebControls.RadioButtonList

    '''<summary>
    '''Eval_EnfrentarData control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Eval_EnfrentarData As Global.System.Web.UI.WebControls.XmlDataSource

    '''<summary>
    '''Eval_DominioPropio control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Eval_DominioPropio As Global.System.Web.UI.WebControls.RadioButtonList

    '''<summary>
    '''Eval_DominioData control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Eval_DominioData As Global.System.Web.UI.WebControls.XmlDataSource

    '''<summary>
    '''Eval_Rectitud control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Eval_Rectitud As Global.System.Web.UI.WebControls.RadioButtonList

    '''<summary>
    '''Eval_IntencionData control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Eval_IntencionData As Global.System.Web.UI.WebControls.XmlDataSource

    '''<summary>
    '''Eval_TomadeDecisiones control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Eval_TomadeDecisiones As Global.System.Web.UI.WebControls.RadioButtonList

    '''<summary>
    '''Eval_DecisionesData control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Eval_DecisionesData As Global.System.Web.UI.WebControls.XmlDataSource

    '''<summary>
    '''Eval_Sinceridad control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Eval_Sinceridad As Global.System.Web.UI.WebControls.RadioButtonList

    '''<summary>
    '''Eval_SinceroData control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Eval_SinceroData As Global.System.Web.UI.WebControls.XmlDataSource

    '''<summary>
    '''Eval_ProySerenidad control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Eval_ProySerenidad As Global.System.Web.UI.WebControls.RadioButtonList

    '''<summary>
    '''Eval_SerenidadData control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Eval_SerenidadData As Global.System.Web.UI.WebControls.XmlDataSource

    '''<summary>
    '''Eval_SentidoComun control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Eval_SentidoComun As Global.System.Web.UI.WebControls.RadioButtonList

    '''<summary>
    '''Eval_SentidoData control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Eval_SentidoData As Global.System.Web.UI.WebControls.XmlDataSource

    '''<summary>
    '''eval_buenJuicio control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents eval_buenJuicio As Global.System.Web.UI.WebControls.RadioButtonList

    '''<summary>
    '''eval_buenJuicioData control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents eval_buenJuicioData As Global.System.Web.UI.WebControls.XmlDataSource

    '''<summary>
    '''Eval_TrabajoComunicacion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Eval_TrabajoComunicacion As Global.System.Web.UI.WebControls.RadioButtonList

    '''<summary>
    '''Eval_TrabajoComunicacionData control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Eval_TrabajoComunicacionData As Global.System.Web.UI.WebControls.XmlDataSource

    '''<summary>
    '''Eval_habilidadCooperacion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Eval_habilidadCooperacion As Global.System.Web.UI.WebControls.RadioButtonList

    '''<summary>
    '''Eval_habilidadCooperacionData control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Eval_habilidadCooperacionData As Global.System.Web.UI.WebControls.XmlDataSource

    '''<summary>
    '''Eval_habilidadEquipo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Eval_habilidadEquipo As Global.System.Web.UI.WebControls.RadioButtonList

    '''<summary>
    '''Eval_habilidadEquipoData control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Eval_habilidadEquipoData As Global.System.Web.UI.WebControls.XmlDataSource

    '''<summary>
    '''Eval_FacilitaDialogo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Eval_FacilitaDialogo As Global.System.Web.UI.WebControls.RadioButtonList

    '''<summary>
    '''Eval_DialogoData control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Eval_DialogoData As Global.System.Web.UI.WebControls.XmlDataSource

    '''<summary>
    '''Eval_EducacionUrbanidad control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Eval_EducacionUrbanidad As Global.System.Web.UI.WebControls.RadioButtonList

    '''<summary>
    '''Eval_urbanidadData control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Eval_urbanidadData As Global.System.Web.UI.WebControls.XmlDataSource

    '''<summary>
    '''Eval_HumorAfabilidad control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Eval_HumorAfabilidad As Global.System.Web.UI.WebControls.RadioButtonList

    '''<summary>
    '''Eval_HumorData control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Eval_HumorData As Global.System.Web.UI.WebControls.XmlDataSource

    '''<summary>
    '''Eval_EscuchaOpinion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Eval_EscuchaOpinion As Global.System.Web.UI.WebControls.RadioButtonList

    '''<summary>
    '''Eval_VistaData control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Eval_VistaData As Global.System.Web.UI.WebControls.XmlDataSource

    '''<summary>
    '''Eval_AyudaOtros control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Eval_AyudaOtros As Global.System.Web.UI.WebControls.RadioButtonList

    '''<summary>
    '''Eval_AjenasData control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Eval_AjenasData As Global.System.Web.UI.WebControls.XmlDataSource

    '''<summary>
    '''Eval_FortaDebilidades control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Eval_FortaDebilidades As Global.System.Web.UI.WebControls.RadioButtonList

    '''<summary>
    '''Eval_ReconocerData control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Eval_ReconocerData As Global.System.Web.UI.WebControls.XmlDataSource

    '''<summary>
    '''Eval_PerservanciaLogros control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Eval_PerservanciaLogros As Global.System.Web.UI.WebControls.RadioButtonList

    '''<summary>
    '''Eval_PerservanciaData control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Eval_PerservanciaData As Global.System.Web.UI.WebControls.XmlDataSource

    '''<summary>
    '''Eval_OralEscrita control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Eval_OralEscrita As Global.System.Web.UI.WebControls.RadioButtonList

    '''<summary>
    '''Eval_OralData control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Eval_OralData As Global.System.Web.UI.WebControls.XmlDataSource

    '''<summary>
    '''Eval_finalRecomienda control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Eval_finalRecomienda As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''XmlDataSource1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents XmlDataSource1 As Global.System.Web.UI.WebControls.XmlDataSource

    '''<summary>
    '''Eval_finalRecomiendatxt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Eval_finalRecomiendatxt As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Eval_button control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Eval_button As Global.System.Web.UI.WebControls.Button
End Class
