'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Oferta

    '''<summary>
    '''For_Date control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents For_Date As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''For_CompanyName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents For_CompanyName As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''For_salary control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents For_salary As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''For_Department control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents For_Department As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''XmlFor_Department control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents XmlFor_Department As Global.System.Web.UI.WebControls.XmlDataSource

    '''<summary>
    '''For_otherBenefits control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents For_otherBenefits As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''For_schedule control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents For_schedule As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''For_requirements control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents For_requirements As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''For_tasks control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents For_tasks As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''For_contactName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents For_contactName As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''For_contactPosition control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents For_contactPosition As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''For_contactPhone control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents For_contactPhone As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''For_contactExt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents For_contactExt As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''For_contactOtherPhone control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents For_contactOtherPhone As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''For_contactFax control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents For_contactFax As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''For_physicalAddress control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents For_physicalAddress As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''For_postalAddress control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents For_postalAddress As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''For_comments control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents For_comments As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''For_email control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents For_email As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''For_webPage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents For_webPage As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''btnGuardarOferta control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnGuardarOferta As Global.System.Web.UI.WebControls.Button
End Class
