'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Oferta

    '''<summary>
    '''For_CompanyName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents For_CompanyName As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''For_Salary control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents For_Salary As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''For_Extracurricular control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents For_Extracurricular As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''XmlExtracurricular control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents XmlExtracurricular As Global.System.Web.UI.WebControls.XmlDataSource

    '''<summary>
    '''For_OtherBenefits control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents For_OtherBenefits As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''For_Schedule control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents For_Schedule As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''For_Requirements control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents For_Requirements As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''For_Tasks control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents For_Tasks As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''For_ContactName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents For_ContactName As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''For_ContactPosition control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents For_ContactPosition As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''For_ContactPhone control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents For_ContactPhone As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''For_ContactExt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents For_ContactExt As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''For_ContactOtherPhone control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents For_ContactOtherPhone As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''For_contactFax control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents For_contactFax As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''For_CompanyPhysicalAddress control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents For_CompanyPhysicalAddress As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''For_CompanyPostalAddress control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents For_CompanyPostalAddress As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''For_Comments control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents For_Comments As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''For_CompanyEmail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents For_CompanyEmail As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''For_CompanyWebPage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents For_CompanyWebPage As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''btnGuardarOferta control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnGuardarOferta As Global.System.Web.UI.WebControls.Button
End Class
