'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class ResultadoEvaluaciones

    '''<summary>
    '''form1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents form1 As Global.System.Web.UI.HtmlControls.HtmlForm

    '''<summary>
    '''Result_NombreEstudiante control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Result_NombreEstudiante As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Result_NumeroEstudiante control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Result_NumeroEstudiante As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Evaluador1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Evaluador1 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Evaluador2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Evaluador2 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Evaluador3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Evaluador3 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Resul_AsociacionEst1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Resul_AsociacionEst1 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Resul_AsociacionEst2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Resul_AsociacionEst2 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Resul_AsociacionEst3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Resul_AsociacionEst3 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Eval_ConoceEs1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Eval_ConoceEs1 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Eval_ConoceEs2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Eval_ConoceEs2 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Eval_ConoceEs3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Eval_ConoceEs3 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Eval_tiempo1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Eval_tiempo1 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Eval_tiempo2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Eval_tiempo2 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Eval_tiempo3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Eval_tiempo3 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Eval_OpinionProfEst1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Eval_OpinionProfEst1 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Eval_OpinionProfEst2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Eval_OpinionProfEst2 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Eval_OpinionProfEst3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Eval_OpinionProfEst3 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Eval_FaltaEst1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Eval_FaltaEst1 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Eval_FaltaEst2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Eval_FaltaEst2 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Eval_FaltaEst3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Eval_FaltaEst3 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Eval_FaltaEsttxt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Eval_FaltaEsttxt As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Eval_FaltaEst2txt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Eval_FaltaEst2txt As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Eval_FaltaEst3txt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Eval_FaltaEst3txt As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Eval_Tarea1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Eval_Tarea1 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Eval_Tarea2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Eval_Tarea2 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Eval_Tarea3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Eval_Tarea3 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Eval_Cumplimiento1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Eval_Cumplimiento1 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Eval_Cumplimiento2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Eval_Cumplimiento2 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Eval_Cumplimiento3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Eval_Cumplimiento3 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Eval_UsoTiempo1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Eval_UsoTiempo1 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Eval_UsoTiempo2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Eval_UsoTiempo2 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Eval_UsoTiempo3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Eval_UsoTiempo3 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Eval_Horario1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Eval_Horario1 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Eval_Horario2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Eval_Horario2 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Eval_Horario3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Eval_Horario3 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Eval_OrdenEstudiante1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Eval_OrdenEstudiante1 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Eval_OrdenEstudiante2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Eval_OrdenEstudiante2 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Eval_OrdenEstudiante3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Eval_OrdenEstudiante3 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Eval_Procedimiento1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Eval_Procedimiento1 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Eval_Procedimiento2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Eval_Procedimiento2 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Eval_Procedimiento3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Eval_Procedimiento3 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Eval_AjustaNormas1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Eval_AjustaNormas1 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Eval_AjustaNormas2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Eval_AjustaNormas2 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Eval_AjustaNormas3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Eval_AjustaNormas3 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Eval_CalidadTrbajo1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Eval_CalidadTrbajo1 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Eval_CalidadTrbajo2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Eval_CalidadTrbajo2 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Eval_CalidadTrbajo3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Eval_CalidadTrbajo3 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Eval_DeleganResponsabilidad1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Eval_DeleganResponsabilidad1 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Eval_DeleganResponsabilidad2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Eval_DeleganResponsabilidad2 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Eval_DeleganResponsabilidad3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Eval_DeleganResponsabilidad3 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Eval_Habilidad_Presion1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Eval_Habilidad_Presion1 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Eval_Habilidad_Presion2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Eval_Habilidad_Presion2 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Eval_Habilidad_Presion3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Eval_Habilidad_Presion3 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Eval_Habilidad_Analisis_Resolver1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Eval_Habilidad_Analisis_Resolver1 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Eval_Habilidad_Analisis_Resolver2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Eval_Habilidad_Analisis_Resolver2 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Eval_Habilidad_Analisis_Resolver3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Eval_Habilidad_Analisis_Resolver3 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Eval_EnfrentarRetos1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Eval_EnfrentarRetos1 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Eval_EnfrentarRetos2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Eval_EnfrentarRetos2 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Eval_EnfrentarRetos3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Eval_EnfrentarRetos3 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Eval_DominioPropio1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Eval_DominioPropio1 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Eval_DominioPropio2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Eval_DominioPropio2 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Eval_DominioPropio3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Eval_DominioPropio3 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Eval_Rectitud1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Eval_Rectitud1 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Eval_Rectitud2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Eval_Rectitud2 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Eval_Rectitud3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Eval_Rectitud3 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Eval_TomadeDecisiones1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Eval_TomadeDecisiones1 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Eval_TomadeDecisiones2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Eval_TomadeDecisiones2 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Eval_TomadeDecisiones3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Eval_TomadeDecisiones3 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Eval_Sinceridad1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Eval_Sinceridad1 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Eval_Sinceridad2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Eval_Sinceridad2 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Eval_Sinceridad3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Eval_Sinceridad3 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Eval_ProySerenidad1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Eval_ProySerenidad1 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Eval_ProySerenidad2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Eval_ProySerenidad2 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Eval_ProySerenidad3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Eval_ProySerenidad3 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Eval_SentidoComun1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Eval_SentidoComun1 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Eval_SentidoComun2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Eval_SentidoComun2 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Eval_SentidoComun3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Eval_SentidoComun3 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''BuenJuicio1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BuenJuicio1 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''BuenJuicio2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BuenJuicio2 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''BuenJuicio3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BuenJuicio3 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Eval_TrabajoComunicacion1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Eval_TrabajoComunicacion1 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Eval_TrabajoComunicacion2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Eval_TrabajoComunicacion2 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Eval_TrabajoComunicacion3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Eval_TrabajoComunicacion3 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Eval_habilidadCooperacion1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Eval_habilidadCooperacion1 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Eval_habilidadCooperacion2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Eval_habilidadCooperacion2 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Eval_habilidadCooperacion3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Eval_habilidadCooperacion3 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Eval_habilidadEquipo1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Eval_habilidadEquipo1 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Eval_habilidadEquipo2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Eval_habilidadEquipo2 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Eval_habilidadEquipo3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Eval_habilidadEquipo3 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Eval_FacilitaDialogo1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Eval_FacilitaDialogo1 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Eval_FacilitaDialogo2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Eval_FacilitaDialogo2 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Eval_FacilitaDialogo3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Eval_FacilitaDialogo3 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Eval_EducacionUrbanidad1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Eval_EducacionUrbanidad1 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Eval_EducacionUrbanidad2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Eval_EducacionUrbanidad2 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Eval_EducacionUrbanidad3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Eval_EducacionUrbanidad3 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Eval_HumorAfabilidad1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Eval_HumorAfabilidad1 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Eval_HumorAfabilidad2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Eval_HumorAfabilidad2 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Eval_HumorAfabilidad3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Eval_HumorAfabilidad3 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Eval_EscuchaOpinion1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Eval_EscuchaOpinion1 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Eval_EscuchaOpinion2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Eval_EscuchaOpinion2 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Eval_EscuchaOpinion3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Eval_EscuchaOpinion3 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Eval_AyudaOtros1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Eval_AyudaOtros1 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Eval_AyudaOtros2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Eval_AyudaOtros2 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Eval_AyudaOtros3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Eval_AyudaOtros3 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Eval_FortaDebilidades1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Eval_FortaDebilidades1 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Eval_FortaDebilidades2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Eval_FortaDebilidades2 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Eval_FortaDebilidades3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Eval_FortaDebilidades3 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Eval_PerservanciaLogros1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Eval_PerservanciaLogros1 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Eval_PerservanciaLogros2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Eval_PerservanciaLogros2 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Eval_PerservanciaLogros3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Eval_PerservanciaLogros3 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Eval_OralEscrita1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Eval_OralEscrita1 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Eval_OralEscrita2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Eval_OralEscrita2 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Eval_OralEscrita3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Eval_OralEscrita3 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Recomienda1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Recomienda1 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Recomienda2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Recomienda2 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Recomieda3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Recomieda3 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''PorqueRecomienda1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PorqueRecomienda1 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''PorqueRecomienda2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PorqueRecomienda2 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''PorqueRecomienda3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PorqueRecomienda3 As Global.System.Web.UI.WebControls.TextBox
End Class
