'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Solicitud

    '''<summary>
    '''StudentName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents StudentName As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''StudentNumber control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents StudentNumber As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Stu_Gender control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Stu_Gender As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''XmlGenero control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents XmlGenero As Global.System.Web.UI.WebControls.XmlDataSource

    '''<summary>
    '''Stu_Email control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Stu_Email As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Stu_Phone control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Stu_Phone As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Stu_Direccion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Stu_Direccion As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Stu_Postal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Stu_Postal As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Stu_Department control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Stu_Department As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''XmlDataSource3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents XmlDataSource3 As Global.System.Web.UI.WebControls.XmlDataSource

    '''<summary>
    '''Sol_Specialty control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Sol_Specialty As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Stu_Year control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Stu_Year As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''XmlYear control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents XmlYear As Global.System.Web.UI.WebControls.XmlDataSource

    '''<summary>
    '''Sol_GraduationDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Sol_GraduationDate As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''XmlGraduationDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents XmlGraduationDate As Global.System.Web.UI.WebControls.XmlDataSource

    '''<summary>
    '''Stu_Igs control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Stu_Igs As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''XmlIGS control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents XmlIGS As Global.System.Web.UI.WebControls.XmlDataSource

    '''<summary>
    '''Sol_Transportation control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Sol_Transportation As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''XmlTransportacion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents XmlTransportacion As Global.System.Web.UI.WebControls.XmlDataSource

    '''<summary>
    '''Sol_License control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Sol_License As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''XmlLicencia control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents XmlLicencia As Global.System.Web.UI.WebControls.XmlDataSource

    '''<summary>
    '''Sol_English control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Sol_English As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''XmlIngles control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents XmlIngles As Global.System.Web.UI.WebControls.XmlDataSource

    '''<summary>
    '''Sol_Resume control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Sol_Resume As Global.System.Web.UI.WebControls.FileUpload

    '''<summary>
    '''Sol_Interest control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Sol_Interest As Global.System.Web.UI.WebControls.CheckBoxList

    '''<summary>
    '''XmlInterest control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents XmlInterest As Global.System.Web.UI.WebControls.XmlDataSource

    '''<summary>
    '''Sol_Availability control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Sol_Availability As Global.System.Web.UI.WebControls.CheckBoxList

    '''<summary>
    '''XmlDisponibilidad control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents XmlDisponibilidad As Global.System.Web.UI.WebControls.XmlDataSource

    '''<summary>
    '''btnGuardarSolicitud control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnGuardarSolicitud As Global.System.Web.UI.WebControls.Button
End Class
