'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class verOfertas_Mem

    '''<summary>
    '''For_CompanyName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents For_CompanyName As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''For_Salary control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents For_Salary As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''For_OtherBenefits control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents For_OtherBenefits As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''For_ContactName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents For_ContactName As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''For_ContactOtherPhone control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents For_ContactOtherPhone As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''For_contactFax control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents For_contactFax As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''For_CompanyPhysicalAddress control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents For_CompanyPhysicalAddress As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''For_CompanyPostalAddress control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents For_CompanyPostalAddress As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''For_Comments control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents For_Comments As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''For_CompanyEmail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents For_CompanyEmail As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''For_CompanyWebPage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents For_CompanyWebPage As Global.System.Web.UI.WebControls.Label
End Class
