'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class verOfertas

    '''<summary>
    '''For_CompanyName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents For_CompanyName As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''For_Salary control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents For_Salary As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''For_CompanyWebPage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents For_CompanyWebPage As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''For_CompanyName1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents For_CompanyName1 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''For_Salary1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents For_Salary1 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''For_CompanyWebPage1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents For_CompanyWebPage1 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''For_ComapanyName2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents For_ComapanyName2 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''For_Salary2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents For_Salary2 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''For_CompanyWebPage2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents For_CompanyWebPage2 As Global.System.Web.UI.WebControls.Label
End Class
